services:
  - type: web
    name: nelonclient
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: node backend/server.js
    envVars:
      - key: PORT
        value: 3000
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
